name: Self-Retriggering Script Runner

on:
  schedule:
    # Initial cron trigger (runs every 5 hours as backup)
    - cron: '0 */5 * * *'
  workflow_dispatch: # Allows manual triggering
  repository_dispatch:
    types: [retrigger] # Custom event for self-retriggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run index.js
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add any other environment variables your script needs
          # CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          
      - name: Wait 5 hours
        run: sleep 18000  # 5 hours = 18000 seconds
        
      - name: Retrigger workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"retrigger"}'